# -*- coding: utf-8 -*-
"""Syntecxhub_Numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ENTj73OeCl6qVZDcEuX_BrNk-LFLlQuK
"""

# Import Libraries

import numpy as np
import time
from sklearn.datasets import load_iris

# Load Iris Dataset

iris = load_iris()

data = iris.data

feature_names = iris.feature_names

print("Dataset Shape:", data.shape)

print("\nFeature Names:")
print(feature_names)

print("\nFirst 5 Rows:")
print(data[:5])

# Array Creation

array1 = np.array([1, 2, 3, 4, 5])

zeros_array = np.zeros((2, 3))

ones_array = np.ones((3, 3))

random_array = np.random.rand(2, 2)

print("1D Array:")
print(array1)

print("\nZeros Array:")
print(zeros_array)

print("\nOnes Array:")
print(ones_array)

print("\nRandom Array:")
print(random_array)

# Indexing and Slicing

print("First Row:")
print(data[0])

print("\nFirst Column:")
print(data[:, 0])

print("\nFirst 10 Rows:")
print(data[:10])

print("\nRows 10 to 20 and Columns 1 to 3:")
print(data[10:20, 1:3])

# Mathematical Operations

addition = data + 2

multiplication = data * 2

square = np.square(data)

print("Addition:")
print(addition[:3])

print("\nMultiplication:")
print(multiplication[:3])

print("\nSquare:")
print(square[:3])

# Axis-wise Operations

column_mean = np.mean(data, axis=0)

row_sum = np.sum(data, axis=1)

column_max = np.max(data, axis=0)

print("Mean of Columns:")
print(column_mean)

print("\nSum of Rows:")
print(row_sum[:10])

print("\nMaximum Values:")
print(column_max)

# Statistical Operations

mean = np.mean(data)

median = np.median(data)

std_dev = np.std(data)

minimum = np.min(data)

maximum = np.max(data)

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)
print("Minimum:", minimum)
print("Maximum:", maximum)

# Reshaping Arrays

reshaped = array1.reshape((5, 1))

flattened = reshaped.flatten()

print("Reshaped Array:")
print(reshaped)

print("\nFlattened Array:")
print(flattened)

# Broadcasting

broadcast_result = data + np.array([1, 1, 1, 1])

print("Broadcasted Result:")
print(broadcast_result[:5])

# Save and Load Arrays

np.save("iris_data.npy", data)

loaded_data = np.load("iris_data.npy")

print("Loaded Data Shape:")
print(loaded_data.shape)

# Performance Comparison

python_list = list(range(1000000))

numpy_array = np.arange(1000000)

# Python List Timing
start = time.time()

python_result = [x * 2 for x in python_list]

end = time.time()

print("Python List Time:", end - start)

# NumPy Timing
start = time.time()

numpy_result = numpy_array * 2

end = time.time()

print("NumPy Array Time:", end - start)

print("NUMPY DATA EXPLORER PROJECT COMPLETED")